### ISSUE TITLE
[Feature request] Please add cloudinit and vmimage support to the autils

### ISSUE THREAD

**Issue by huth** [avocado-framework/aautils#22]
For the functional tests in QEMU, it would be great to have the cloudinit and vmimage modules from avocado.utils in the autils, so the tests that are based on this code could be used independently of the avocado test runner, too:

* https://gitlab.com/qemu-project/qemu/-/blob/v9.1.0/tests/avocado/avocado_qemu/linuxtest.py
* https://gitlab.com/qemu-project/qemu/-/blob/v9.1.0/tests/avocado/replay_linux.py

So please add the cloudinit and vmimage module to the autils (this likely also includes the iso9660 module from avocado.utils since the couldinit code is using it internally). Thanks!

**Comment by richtja** [comment]
This issue is dependent on finishing autils initialization described in #1

**Comment by huth** [comment]
I recently found a rather easy way to also use the Fedora cloud images without the cloudinit module from Avocado, so this is not urgently required anymore. Thus closing the request.
